#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: $(basename $0) <version>" >&2
    exit 1
fi

vers=$1
git archive --format=tar --prefix=netdumpd-${vers}/ master | \
    gzip > netdumpd-${vers}.tar.gz
