#!/bin/sh

if [ $# -ne 0 ]; then
    echo "usage: $(basename $0)" >&2
    exit 1
fi

pkg=netdumpd-$(date +"%Y%m%d")
file=${pkg}.tar.gz
git archive --format=tar --prefix=${pkg}/ master | gzip > $file
scp $file markj@freefall.freebsd.org:public_distfiles/
