#!/bin/sh

if [ $# -ne 0 ]; then
    echo "usage: $(basename $0)" >&2
    exit 1
fi

vers=$(date +"%Y%m%d")
git archive --format=tar --prefix=netdumpd-${vers}/ master | \
    gzip > netdumpd-${vers}.tar.gz
