#!/bin/sh

# PROVIDE: netdumpd
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="netdumpd"
: ${netdumpd_enable=NO}
rcvar="netdumpd_enable"
rcflags="${netdumpd_flags}"
command="/usr/local/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
